-- Milestone 3.2 Work Item 10 (docs/hardening/milestone-3.2-work-item-10-
-- role-catalog-validation-proposal.md) — a fixed allow-list CHECK on
-- users.roles. Drizzle's schema DSL has no builder for an array-containment
-- CHECK constraint, hence this hand-written file, applied the same way
-- sphere-finance's drizzle/constraints/*.sql is (see apply-db-constraints.ts
-- in this package, mirroring services/sphere-finance/src/db/
-- apply-db-constraints.ts).
--
-- The `<@` (is contained by) array operator rejects any INSERT/UPDATE whose
-- roles array contains a value outside the fixed list below, while still
-- permitting an empty array ('{}' — every PLATFORM_OPERATOR row, and any
-- TENANT_INTERNAL/TENANT_EXTERNAL row not yet granted a Finance role) and
-- any subset or repetition of the allowed values. This is a second,
-- independent enforcement of exactly the set hasRequiredRole()
-- (packages/auth-core/src/authorization.ts) already treats as meaningful —
-- the same defense-in-depth pattern Milestone 3.1 used for tenant isolation
-- (RLS as a second layer behind application-level tenant checks).
--
-- Only the three role strings actually enforced anywhere in the platform
-- today are allowed (confirmed by repository-wide search across every
-- @Roles(...) call site and both noryx.module.json manifests — see the
-- Work Item 10 proposal §2). Neither "finance.approver" nor
-- "orbis.technician" — the two illustrative examples in this column's own
-- schema.ts comment — is a real, enforced role; deliberately excluded.
--
-- Adding a new role in the future requires a NEW migration file appended
-- here (e.g. 002_role_catalog_add_<role>.sql that re-applies the
-- constraint with an extended list) — this is intentional, per the
-- proposal's §16 Q2 framing ("a known set"): a pattern-based/open check
-- would defeat the purpose of a catalog. Do not edit this file's list
-- in place for a future change; add a new versioned file instead, the
-- same convention drizzle/rls/*.sql and drizzle/constraints/*.sql already
-- follow elsewhere in this repository.

ALTER TABLE users
  DROP CONSTRAINT IF EXISTS users_roles_catalog_check;

ALTER TABLE users
  ADD CONSTRAINT users_roles_catalog_check
  CHECK (roles <@ ARRAY['finance.viewer', 'finance.poster', 'finance.admin']::text[]);
